name: 'GitHub Actions Email Bot'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
 
jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        run: bash ./main.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: gfgdf
          body: file://emailtext.txt
          to: ${{ secrets.RECEIVER }}
          from: YOUR OLD BABY
          content_type: text/plain
